### ISSUE TITLE
타입스크립트로 넘어가기

### ISSUE THREAD

**Issue by scarf005** [Together42/backend#102]
## description
> 타입 힌트를 통해 코드의 가독성과 안정성을 올리면 좋을 것 같아오
## todo
- [ ] `*.js` 폴더를 `src/` 폴더로 옮기고, 컴파일된 폴더를 담을 `dist/` 폴더 추가하기
- [ ] `package.json`에 타입스크립트 타입 힌트 추가
- [ ] 타입스크립트로 코드 변경

**Comment by kth2624** [comment]
좋습니다!

**Comment by kth2624** [comment]
일단 보류
